'use client';
import {useEffect,useRef,useState} from 'react';
import Shell from '../../components/DashboardShell';
import {api} from '../../lib/api';
type Msg={role:'user'|'assistant';content:string}; const STORE='creator-studio-chat';
export default function ChatPage(){const[messages,setMessages]=useState<Msg[]>([]);const[input,setInput]=useState('');const[busy,setBusy]=useState(false);const[coins,setCoins]=useState(0);const end=useRef<HTMLDivElement>(null);
useEffect(()=>{try{setMessages(JSON.parse(localStorage.getItem(STORE)||'[]'))}catch{};api('/wallet').then(x=>setCoins(x.coinBalance)).catch(()=>{})},[]);useEffect(()=>{localStorage.setItem(STORE,JSON.stringify(messages));end.current?.scrollIntoView({behavior:'smooth'})},[messages]);
async function wait(id:string){for(let i=0;i<90;i++){await new Promise(r=>setTimeout(r,1200));const j=await api('/jobs/'+id);if(j.status==='completed')return j.result?.answer||j.result?.description||JSON.stringify(j.result);if(j.status==='failed')throw new Error(j.error_message||'Generation failed')}throw new Error('Response is taking too long. Please try again.');}
async function send(){const text=input.trim();if(!text||busy)return;const next=[...messages,{role:'user' as const,content:text}];setMessages(next);setInput('');setBusy(true);try{const job=await api('/ai/chat',{method:'POST',body:JSON.stringify({message:text,history:next.slice(-12)})});const answer=await wait(job.id);setMessages(m=>[...m,{role:'assistant',content:String(answer)}]);api('/wallet').then(x=>setCoins(x.coinBalance)).catch(()=>{});}catch(e:any){setMessages(m=>[...m,{role:'assistant',content:'⚠️ '+e.message}]);}finally{setBusy(false)}}
function fresh(){setMessages([]);localStorage.removeItem(STORE)}
return <Shell><div className="chatPage"><div className="chatTop"><div><span className="rainbowDot">✦</span><b> Creator AI</b><small> Gemini powered</small></div><div className="chatActions"><span className="coinBadge">🪙 {coins}</span><button className="miniBtn" onClick={fresh}>＋ New Chat</button></div></div><div className="chatBody">{messages.length===0&&<div className="welcome"><div className="aiOrb">✦</div><h1>How can I help you create?</h1><p>Titles, descriptions, tags, scripts, ideas, SEO and creator help — ask everything in one chat.</p><div className="suggestions"><button onClick={()=>setInput('Mere YouTube live ke liye 10 jabardast title do')}>🔴 Live titles</button><button onClick={()=>setInput('Mere video ke liye SEO description banao')}>🔵 SEO description</button><button onClick={()=>setInput('Mere YouTube video ke liye best tags do')}>🟡 Tags</button><button onClick={()=>setInput('Mere channel ke liye content ideas do')}>🩷 Content ideas</button></div></div>}{messages.map((m,i)=><div className={'message '+m.role} key={i}><div className="avatar">{m.role==='assistant'?'✦':'You'}</div><div className="bubble"><div className="msgText">{m.content}</div>{m.role==='assistant'&&<button className="copyBtn" onClick={()=>navigator.clipboard.writeText(m.content)}>⧉ Copy</button>}</div></div>)}{busy&&<div className="message assistant"><div className="avatar">✦</div><div className="bubble typing"><i></i><i></i><i></i></div></div>}<div ref={end}/></div><div className="composerWrap"><div className="composer"><button className="attach" title="Attachment">＋</button><textarea value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}}} placeholder="Message Creator AI…" rows={1}/><button className="sendBtn" disabled={busy||!input.trim()} onClick={send}>➤</button></div><div className="composerNote">Creator AI can make mistakes. Check important information.</div></div></div></Shell>}
