'use client';
import {useEffect,useRef,useState} from 'react';
import Shell from '../../components/DashboardShell';
import {api} from '../../lib/api';
type Msg={role:'user'|'assistant';content:string}; const STORE='khobragade-ai-chat';
export default function ChatPage(){
 const[messages,setMessages]=useState<Msg[]>([]),[input,setInput]=useState(''),[busy,setBusy]=useState(false),[coins,setCoins]=useState(0),[listening,setListening]=useState(false),[voiceMode,setVoiceMode]=useState(false),[voiceGender,setVoiceGender]=useState<'female'|'male'>('female');
 const end=useRef<HTMLDivElement>(null),rec=useRef<any>(null),voiceModeRef=useRef(false),restartTimer=useRef<any>(null),busyRef=useRef(false),messagesRef=useRef<Msg[]>([]),voiceGenderRef=useRef<'female'|'male'>('female');
 useEffect(()=>{try{setMessages(JSON.parse(localStorage.getItem(STORE)||'[]'))}catch{};api('/wallet').then(x=>setCoins(x.coinBalance)).catch(()=>{});return()=>{rec.current?.stop?.();speechSynthesis?.cancel?.()}},[]);
 useEffect(()=>{localStorage.setItem(STORE,JSON.stringify(messages));end.current?.scrollIntoView({behavior:'smooth'})},[messages]);
 useEffect(()=>{voiceModeRef.current=voiceMode},[voiceMode]);
 useEffect(()=>{busyRef.current=busy},[busy]);
 useEffect(()=>{messagesRef.current=messages},[messages]);
 useEffect(()=>{voiceGenderRef.current=voiceGender;localStorage.setItem('kh_voice_gender',voiceGender)},[voiceGender]);
 useEffect(()=>{const v=localStorage.getItem('kh_voice_gender');if(v==='male'||v==='female')setVoiceGender(v)},[]);
 async function wait(id:string){for(let i=0;i<90;i++){await new Promise(r=>setTimeout(r,1200));const j=await api('/jobs/'+id);if(j.status==='completed')return j.result?.answer||j.result?.description||JSON.stringify(j.result);if(j.status==='failed')throw new Error(j.error_message||'Generation failed')}throw new Error('Response is taking too long. Please try again.');}
 function speak(text:string,continueVoice=false){if(typeof window==='undefined'||!('speechSynthesis'in window))return;window.speechSynthesis.cancel();window.speechSynthesis.resume();const u=new SpeechSynthesisUtterance(text);const lang=/[\u0900-\u097F]/.test(text)?'hi-IN':'en-IN';u.lang=lang;const chooseVoice=()=>{const vs=window.speechSynthesis.getVoices();const preferred=vs.find(v=>v.lang.toLowerCase().startsWith(lang.slice(0,2).toLowerCase())&&(voiceGenderRef.current==='female'?/female|heera|swara|veena|zira|samantha/i:/male|ravi|hemant|david|mark/i).test(v.name))||vs.find(v=>v.lang.toLowerCase().startsWith(lang.slice(0,2).toLowerCase()));if(preferred)u.voice=preferred;};chooseVoice();u.onend=()=>{if(continueVoice&&voiceModeRef.current){clearTimeout(restartTimer.current);restartTimer.current=setTimeout(()=>startMic(true),450)}};u.onerror=()=>{};window.speechSynthesis.speak(u)}
 async function send(textOverride?:string,speakReply=false){const text=(textOverride??input).trim();if(!text||busyRef.current)return;busyRef.current=true;const next=[...messagesRef.current,{role:'user' as const,content:text}];messagesRef.current=next;setMessages(next);setInput('');setBusy(true);try{const job=await api('/ai/chat',{method:'POST',body:JSON.stringify({message:text,history:next.slice(-20),voiceGender:voiceGenderRef.current})});const answer=String(await wait(job.id));setMessages(m=>{const v=[...m,{role:'assistant' as const,content:answer}];messagesRef.current=v;return v});if(speakReply||voiceModeRef.current)speak(answer,voiceModeRef.current);api('/wallet').then(x=>setCoins(x.coinBalance)).catch(()=>{});}catch(e:any){setMessages(m=>[...m,{role:'assistant',content:'⚠️ '+e.message}]);}finally{busyRef.current=false;setBusy(false)}}
 function startMic(autoSend=false){const W:any=window;const SR=W.SpeechRecognition||W.webkitSpeechRecognition;if(!SR){alert('Voice input is not supported in this browser. Please use Chrome/Edge or the Android app.');return}if(rec.current){try{rec.current.stop()}catch{};rec.current=null}window.speechSynthesis?.cancel();const r=new SR();rec.current=r;r.lang='hi-IN';r.interimResults=true;r.continuous=false;r.onstart=()=>setListening(true);r.onend=()=>{setListening(false);rec.current=null};r.onerror=()=>{setListening(false);rec.current=null};r.onresult=(e:any)=>{let t='';for(let i=e.resultIndex;i<e.results.length;i++)t+=e.results[i][0].transcript;setInput(t);if(e.results[e.results.length-1].isFinal&&autoSend)setTimeout(()=>send(t,true),100)};r.start()}
 function toggleVoice(){if(voiceModeRef.current){voiceModeRef.current=false;setVoiceMode(false);clearTimeout(restartTimer.current);rec.current?.stop?.();rec.current=null;window.speechSynthesis?.cancel();return}voiceModeRef.current=true;setVoiceMode(true);setTimeout(()=>startMic(true),80)}
 function fresh(){setMessages([]);localStorage.removeItem(STORE);clearTimeout(restartTimer.current);window.speechSynthesis?.cancel()}
 return <Shell><div className="chatPage"><div className="chatTop"><div><span className="rainbowDot">✦</span><b> ✨ Khobragade AI</b><small> Your Smart AI Assistant</small></div><div className="chatActions"><span className="coinBadge">🪙 {coins}</span><select className="voiceSelect" value={voiceGender} onChange={e=>setVoiceGender(e.target.value as any)}><option value="female">👩 Female</option><option value="male">👨 Male</option></select><button className="miniBtn" onClick={fresh}>＋ New Chat</button></div></div><div className="chatBody">{messages.length===0&&<div className="welcome"><div className="aiOrb">✦</div><h1>✨ Khobragade AI</h1><p>Ask anything — general questions, study, writing, coding, business, proposals, translation, YouTube, ideas and everyday help.</p><div className="suggestions"><button onClick={()=>setInput('Mere liye ek professional business proposal banao')}>🟢 Business proposal</button><button onClick={()=>setInput('Mujhe kisi topic ko aasan Hindi me samjhao')}>🔵 Explain anything</button><button onClick={()=>setInput('Mere liye professional application likho')}>🟡 Writing help</button><button onClick={()=>setInput('Mere YouTube channel ke liye ideas do')}>🩷 YouTube ideas</button></div></div>}{messages.map((m,i)=><div className={'message '+m.role} key={i}><div className="avatar">{m.role==='assistant'?'✦':'You'}</div><div className="bubble"><div className="msgText">{m.content}</div>{m.role==='assistant'&&<div className="msgActions"><button className="copyBtn" onClick={()=>navigator.clipboard.writeText(m.content)}>⧉ Copy</button><button className="copyBtn" onClick={()=>speak(m.content)}>🔊 Listen</button><button className="copyBtn" onClick={()=>window.speechSynthesis?.cancel()}>⏹ Stop</button></div>}</div></div>)}{busy&&<div className="message assistant"><div className="avatar">✦</div><div className="bubble typing"><i></i><i></i><i></i></div></div>}<div ref={end}/></div><div className="composerWrap"><div className="composer"><button className="attach" title="Attachment">＋</button><textarea value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}}} placeholder="Message ✨ Khobragade AI…" rows={1}/><button className={'micBtn '+(listening?'listening':'')} onClick={()=>startMic(false)} title="Voice typing"><span className="micGlyph">🎤</span></button><button className={'voiceOrb '+(voiceMode?'active':'')} onClick={toggleVoice} title="Voice conversation"><span className="waveBars"><i></i><i></i><i></i><i></i><i></i></span></button><button className="sendBtn" disabled={busy||!input.trim()} onClick={()=>send()}>➤</button></div><div className="composerNote">✨ Khobragade AI can make mistakes. Check important information.</div></div></div></Shell>}
