import 'dart:async';
import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:speech_to_text/speech_to_text.dart' as stt;
import 'package:flutter_tts/flutter_tts.dart';
import '../api.dart';
class ChatScreen extends StatefulWidget{const ChatScreen({super.key});@override State<ChatScreen> createState()=>_ChatScreenState();}
class _ChatScreenState extends State<ChatScreen>{
 final api=Api(),input=TextEditingController(),scroll=ScrollController(),speech=stt.SpeechToText(),tts=FlutterTts();List<Map<String,String>> messages=[];bool busy=false,listening=false,voiceMode=false;int coins=0;String voiceGender='female';
 @override void initState(){super.initState();load();}
 @override void dispose(){speech.stop();tts.stop();input.dispose();scroll.dispose();super.dispose();}
 Future<void> load()async{final p=await SharedPreferences.getInstance();final saved=p.getStringList('khobragade_ai_chat')??[];for(final x in saved){final k=x.indexOf('|');if(k>0)messages.add({'role':x.substring(0,k),'content':x.substring(k+1)});}voiceMode=p.getBool('kh_voice_mode')??false;voiceGender=p.getString('kh_voice_gender')??'female';try{final w=await api.request('/wallet');coins=(w['coinBalance']??0) as int;}catch(_){}if(mounted)setState((){});}
 Future<void> save()async{final p=await SharedPreferences.getInstance();await p.setStringList('khobragade_ai_chat',messages.map((m)=>'${m['role']}|${m['content']}').toList());await p.setBool('kh_voice_mode',voiceMode);await p.setString('kh_voice_gender',voiceGender);}
 Future<String> waitJob(String id)async{for(var i=0;i<90;i++){await Future.delayed(const Duration(milliseconds:1200));final j=await api.request('/jobs/$id');if(j['status']=='completed')return(j['result']?['answer']??j['result']?['description']??'').toString();if(j['status']=='failed')throw Exception(j['error_message']??'Generation failed');}throw Exception('Response is taking too long');}
 Future<void> speak(String text,{bool continueVoice=false})async{await tts.stop();await tts.awaitSpeakCompletion(true);await tts.setLanguage(RegExp(r'[\u0900-\u097F]').hasMatch(text)?'hi-IN':'en-IN');await tts.setSpeechRate(.48);final voices=await tts.getVoices;try{final list=List<Map>.from(voices as List);final wanted=list.where((v){final n='${v['name']}'.toLowerCase();return voiceGender=='female'?RegExp('female|heera|swara|veena|zira').hasMatch(n):RegExp('male|ravi|hemant|david|mark').hasMatch(n);}).toList();if(wanted.isNotEmpty)await tts.setVoice({'name':'${wanted.first['name']}','locale':'${wanted.first['locale']}'});}catch(_){}await tts.speak(text);if(continueVoice&&voiceMode&&mounted){await Future.delayed(const Duration(milliseconds:250));await mic();}}
 Future<void> send([String? value,bool speakReply=false])async{final text=(value??input.text).trim();if(text.isEmpty||busy)return;setState((){messages.add({'role':'user','content':text});input.clear();busy=true;});await save();try{final history=messages.length>20?messages.sublist(messages.length-20):messages;final job=await api.request('/ai/chat',method:'POST',body:{'message':text,'history':history});final answer=await waitJob(job['id'].toString());setState(()=>messages.add({'role':'assistant','content':answer}));if(speakReply||voiceMode)await speak(answer,continueVoice:voiceMode);final w=await api.request('/wallet');coins=(w['coinBalance']??coins) as int;}catch(e){setState(()=>messages.add({'role':'assistant','content':'⚠️ ${e.toString().replaceFirst('Exception: ','')}'}));}finally{busy=false;await save();if(mounted)setState((){});Future.delayed(const Duration(milliseconds:100),()=>scroll.hasClients?scroll.animateTo(scroll.position.maxScrollExtent,duration:const Duration(milliseconds:250),curve:Curves.easeOut):null);}}
 Future<void> mic()async{if(listening){await speech.stop();setState(()=>listening=false);return;}final ok=await speech.initialize(onStatus:(s){if(mounted)setState(()=>listening=s=='listening');});if(!ok)return;setState(()=>listening=true);await speech.listen(localeId:'hi_IN',onResult:(r){input.text=r.recognizedWords;input.selection=TextSelection.collapsed(offset:input.text.length);setState((){});if(r.finalResult)send(r.recognizedWords,true);});}
 Future<void> fresh()async{messages=[];await tts.stop();await save();setState((){});}
 @override Widget build(BuildContext context)=>Scaffold(backgroundColor:const Color(0xfff8f9fc),appBar:AppBar(backgroundColor:Colors.white,title:const Row(children:[Icon(Icons.auto_awesome,color:Colors.pink),SizedBox(width:8),Text('✨ Khobragade AI',style:TextStyle(fontWeight:FontWeight.w800))]),actions:[Center(child:Text('🪙 $coins',style:const TextStyle(fontWeight:FontWeight.bold))),PopupMenuButton<String>(icon:Icon(voiceGender=='female'?Icons.woman:Icons.man),onSelected:(v){voiceGender=v;save();setState((){});},itemBuilder:(_)=>const[PopupMenuItem(value:'female',child:Text('👩 Female voice')),PopupMenuItem(value:'male',child:Text('👨 Male voice'))]),IconButton(onPressed:()async{if(voiceMode){voiceMode=false;await speech.stop();await tts.stop();await save();if(mounted)setState((){});return;}voiceMode=true;await save();if(mounted)setState((){});await mic();},icon:Icon(voiceMode?Icons.record_voice_over:Icons.voice_over_off,color:voiceMode?Colors.green:null)),IconButton(onPressed:fresh,icon:const Icon(Icons.add_comment_outlined))]),body:Column(children:[Expanded(child:messages.isEmpty?_welcome():ListView.builder(controller:scroll,padding:const EdgeInsets.all(14),itemCount:messages.length+(busy?1:0),itemBuilder:(c,i)=>i==messages.length?_bubble({'role':'assistant','content':'•••'}):_bubble(messages[i]))),_composer()]));
 Widget _welcome()=>ListView(padding:const EdgeInsets.all(24),children:[const SizedBox(height:55),const Icon(Icons.auto_awesome,size:56,color:Colors.blue),const SizedBox(height:14),const Text('✨ Khobragade AI',textAlign:TextAlign.center,style:TextStyle(fontSize:28,fontWeight:FontWeight.w800)),const SizedBox(height:10),const Text('Ask anything — general questions, study, writing, coding, business, proposals, translation, YouTube and everyday help.',textAlign:TextAlign.center,style:TextStyle(color:Colors.black54,height:1.5))]);
 Widget _bubble(Map<String,String> m){final user=m['role']=='user';return Align(alignment:user?Alignment.centerRight:Alignment.centerLeft,child:Container(margin:const EdgeInsets.only(bottom:14),constraints:const BoxConstraints(maxWidth:620),padding:const EdgeInsets.all(14),decoration:BoxDecoration(color:user?Colors.black:Colors.white,border:user?null:Border.all(color:Colors.blue.shade100),borderRadius:BorderRadius.circular(18)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[SelectableText(m['content']??'',style:TextStyle(color:user?Colors.white:Colors.black87,height:1.45)),if(!user)Row(mainAxisSize:MainAxisSize.min,children:[IconButton(onPressed:()=>speak(m['content']??''),icon:const Icon(Icons.volume_up,size:18)),IconButton(onPressed:tts.stop,icon:const Icon(Icons.stop,size:18))])])));}
 Widget _composer()=>SafeArea(top:false,child:Container(color:Colors.white,padding:const EdgeInsets.all(12),child:Container(decoration:BoxDecoration(border:Border.all(color:Colors.blue,width:2),borderRadius:BorderRadius.circular(20)),child:Row(crossAxisAlignment:CrossAxisAlignment.end,children:[IconButton(onPressed:(){},icon:const Icon(Icons.add_circle_outline,color:Colors.green)),Expanded(child:TextField(controller:input,minLines:1,maxLines:5,decoration:const InputDecoration(hintText:'Message ✨ Khobragade AI…',border:InputBorder.none))),IconButton(onPressed:mic,icon:Icon(listening?Icons.mic:Icons.mic_none,color:listening?Colors.red:Colors.blue)),IconButton(onPressed:busy?null:()=>send(),icon:const CircleAvatar(backgroundColor:Colors.red,child:Icon(Icons.arrow_upward,color:Colors.white))) ]))));
}
