import 'dart:async';
import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';
import '../api.dart';

class ChatScreen extends StatefulWidget { const ChatScreen({super.key}); @override State<ChatScreen> createState()=>_ChatScreenState(); }
class _ChatScreenState extends State<ChatScreen>{
 final api=Api(), input=TextEditingController(), scroll=ScrollController(); List<Map<String,String>> messages=[]; bool busy=false; int coins=0;
 final colors=[Colors.green,Colors.amber,Colors.pink,Colors.red,Colors.blue,Colors.black,Colors.white];
 @override void initState(){super.initState();load();}
 Future<void> load()async{final p=await SharedPreferences.getInstance();final saved=p.getStringList('creator_chat')??[];for(final x in saved){final k=x.indexOf('|');if(k>0)messages.add({'role':x.substring(0,k),'content':x.substring(k+1)});}try{final w=await api.request('/wallet');coins=(w['coinBalance']??0) as int;}catch(_){ }if(mounted)setState((){});}
 Future<void> save()async{final p=await SharedPreferences.getInstance();await p.setStringList('creator_chat',messages.map((m)=>'${m['role']}|${m['content']}').toList());}
 Future<String> waitJob(String id)async{for(var i=0;i<90;i++){await Future.delayed(const Duration(milliseconds:1200));final j=await api.request('/jobs/$id');if(j['status']=='completed')return (j['result']?['answer']??j['result']?['description']??'').toString();if(j['status']=='failed')throw Exception(j['error_message']??'Generation failed');}throw Exception('Response is taking too long');}
 Future<void> send()async{final text=input.text.trim();if(text.isEmpty||busy)return;setState((){messages.add({'role':'user','content':text});input.clear();busy=true;});await save();try{final history=messages.length>12?messages.sublist(messages.length-12):messages;final job=await api.request('/ai/chat',method:'POST',body:{'message':text,'history':history});final answer=await waitJob(job['id'].toString());setState(()=>messages.add({'role':'assistant','content':answer}));final w=await api.request('/wallet');coins=(w['coinBalance']??coins) as int;}catch(e){setState(()=>messages.add({'role':'assistant','content':'⚠️ ${e.toString().replaceFirst('Exception: ','')}'}));}finally{busy=false;await save();if(mounted)setState((){});Future.delayed(const Duration(milliseconds:100),()=>scroll.hasClients?scroll.animateTo(scroll.position.maxScrollExtent,duration:const Duration(milliseconds:250),curve:Curves.easeOut):null);}}
 Future<void> fresh()async{messages=[];await save();setState((){});}
 @override Widget build(BuildContext context)=>Scaffold(backgroundColor:const Color(0xfff8f9fc),appBar:AppBar(backgroundColor:Colors.white,title:const Row(children:[Icon(Icons.auto_awesome,color:Colors.pink),SizedBox(width:8),Text('Creator AI',style:TextStyle(fontWeight:FontWeight.w800))]),actions:[Center(child:Container(padding:const EdgeInsets.symmetric(horizontal:10,vertical:7),decoration:BoxDecoration(color:Colors.amber.shade100,borderRadius:BorderRadius.circular(20)),child:Text('🪙 $coins',style:const TextStyle(fontWeight:FontWeight.bold)))),IconButton(onPressed:fresh,icon:const Icon(Icons.add_comment_outlined),tooltip:'New Chat')]),body:Column(children:[Expanded(child:messages.isEmpty?_welcome():ListView.builder(controller:scroll,padding:const EdgeInsets.fromLTRB(14,18,14,20),itemCount:messages.length+(busy?1:0),itemBuilder:(c,i){if(i==messages.length)return _bubble({'role':'assistant','content':'•••'});return _bubble(messages[i]);})),_composer()]));
 Widget _welcome()=>ListView(padding:const EdgeInsets.all(24),children:[const SizedBox(height:60),const Icon(Icons.auto_awesome,size:56,color:Colors.blue),const SizedBox(height:16),const Text('How can I help you create?',textAlign:TextAlign.center,style:TextStyle(fontSize:28,fontWeight:FontWeight.w800)),const SizedBox(height:10),const Text('Titles, descriptions, tags, scripts, SEO and creator help — all in one chat.',textAlign:TextAlign.center,style:TextStyle(color:Colors.black54,height:1.5)),const SizedBox(height:28),...['🔴 Live titles','🔵 SEO description','🟡 Best tags','🩷 Content ideas'].asMap().entries.map((e)=>Card(shape:RoundedRectangleBorder(side:BorderSide(color:colors[e.key]),borderRadius:BorderRadius.circular(16)),child:ListTile(title:Text(e.value),trailing:const Icon(Icons.arrow_forward),onTap:(){input.text=['Mere YouTube live ke liye 10 jabardast title do','Mere video ke liye SEO description banao','Mere YouTube video ke liye best tags do','Mere channel ke liye content ideas do'][e.key];}}))]);
 Widget _bubble(Map<String,String> m){final user=m['role']=='user';return Align(alignment:user?Alignment.centerRight:Alignment.centerLeft,child:Container(margin:const EdgeInsets.only(bottom:14),constraints:const BoxConstraints(maxWidth:620),padding:const EdgeInsets.all(14),decoration:BoxDecoration(color:user?Colors.black:Colors.white,border:user?null:Border.all(color:Colors.blue.shade100),borderRadius:BorderRadius.circular(18)),child:SelectableText(m['content']??'',style:TextStyle(color:user?Colors.white:Colors.black87,height:1.45))));}
 Widget _composer()=>SafeArea(top:false,child:Container(color:Colors.white,padding:const EdgeInsets.fromLTRB(12,10,12,12),child:Container(decoration:BoxDecoration(border:Border.all(color:Colors.blue,width:2),borderRadius:BorderRadius.circular(20)),child:Row(crossAxisAlignment:CrossAxisAlignment.end,children:[IconButton(onPressed:(){},icon:const Icon(Icons.add_circle_outline,color:Colors.green)),Expanded(child:TextField(controller:input,minLines:1,maxLines:5,textInputAction:TextInputAction.newline,decoration:const InputDecoration(hintText:'Message Creator AI…',border:InputBorder.none,contentPadding:EdgeInsets.symmetric(vertical:13)))),IconButton(onPressed:busy?null:send,icon:const CircleAvatar(backgroundColor:Colors.red,child:Icon(Icons.arrow_upward,color:Colors.white))) ]))));
}
