import 'package:flutter/material.dart';
import 'api.dart';

class AdminPanelScreen extends StatefulWidget {
  final Future<void> Function() onLogout;
  const AdminPanelScreen({super.key, required this.onLogout});
  @override State<AdminPanelScreen> createState()=>_AdminPanelScreenState();
}

class _AdminPanelScreenState extends State<AdminPanelScreen>{
  final api=Api(); int tab=0; bool loading=true; String error='';
  Map<String,dynamic> report={}; List<dynamic> users=[]; List<dynamic> payments=[]; List<dynamic> cms=[];
  @override void initState(){super.initState();load();}
  Future<void> load()async{setState(()=>loading=true);error='';try{final r=await api.request('/admin/reports');final u=await api.request('/admin/users');final p=await api.request('/admin/payments');final c=await api.request('/admin/cms/app?includeDeleted=true');if(mounted)setState((){report=Map<String,dynamic>.from(r);users=_asList(u,'users');payments=_asList(p,'payments');cms=_asList(c,'items');loading=false;});}catch(e){if(mounted)setState((){error=e.toString().replaceFirst('Exception: ','');loading=false;});}}
  List<dynamic> _asList(Map<String,dynamic> data,String key){final v=data[key] ?? data['data'];return v is List ? v : const <dynamic>[];}
  @override Widget build(BuildContext context)=>Scaffold(
    backgroundColor:const Color(0xfff6f8fc),
    appBar:AppBar(title:const Text('Khobragade AI • Admin CMS',style:TextStyle(fontWeight:FontWeight.w800)),actions:[IconButton(onPressed:load,icon:const Icon(Icons.refresh_rounded)),IconButton(onPressed:widget.onLogout,icon:const Icon(Icons.logout_rounded))]),
    body:loading?const Center(child:CircularProgressIndicator()):error.isNotEmpty?Center(child:Padding(padding:const EdgeInsets.all(24),child:Column(mainAxisSize:MainAxisSize.min,children:[Text(error,textAlign:TextAlign.center),const SizedBox(height:12),FilledButton(onPressed:load,child:const Text('Retry'))]))):_body(),
    bottomNavigationBar:NavigationBar(selectedIndex:tab,onDestinationSelected:(v)=>setState(()=>tab=v),destinations:const[NavigationDestination(icon:Icon(Icons.dashboard_outlined),label:'Dashboard'),NavigationDestination(icon:Icon(Icons.people_outline),label:'Users'),NavigationDestination(icon:Icon(Icons.payments_outlined),label:'Payments'),NavigationDestination(icon:Icon(Icons.auto_awesome_outlined),label:'AI'),NavigationDestination(icon:Icon(Icons.tune_outlined),label:'App CMS')]),
  );
  Widget _body(){if(tab==1)return _users();if(tab==2)return _payments();if(tab==3)return _ai();if(tab==4)return _cms();return _dashboard();}
  Widget _dashboard()=>RefreshIndicator(onRefresh:load,child:ListView(padding:const EdgeInsets.all(16),children:[const Text('Admin Dashboard',style:TextStyle(fontSize:26,fontWeight:FontWeight.w900)),const SizedBox(height:16),Wrap(spacing:10,runSpacing:10,children:[_stat('Users',report['total_users']),_stat('Active',report['active_users']),_stat('Revenue', '₹${report['total_revenue']??0}'),_stat('AI Jobs',report['ai_generations']),_stat('Failed',report['failed_jobs']),_stat('Pending',report['pending_payments'])]),const SizedBox(height:20),_card('Admin CMS App','Manage users, payments, AI controls, maintenance and App CMS from this app.'),_card('Role','Logged in as administrator. User accounts cannot access this panel.')]));
  Widget _users()=>ListView.builder(padding:const EdgeInsets.all(12),itemCount:users.length,itemBuilder:(c,i){final u=Map<String,dynamic>.from(users[i]);return Card(child:ListTile(title:Text('${u['name']??''}',style:const TextStyle(fontWeight:FontWeight.w700)),subtitle:Text('${u['email']??''}\nCoins: ${u['coin_balance']??0} • ${u['status']??''}'),isThreeLine:true,trailing:PopupMenuButton<String>(onSelected:(v)async{if(v=='block'||v=='active'){try{await api.request('/admin/users/${u['id']}/status',method:'POST',body:{'status':v});load();}catch(e){_snack(e.toString());}}},itemBuilder:(_)=>const[PopupMenuItem(value:'active',child:Text('Set Active')),PopupMenuItem(value:'block',child:Text('Block'))])));});
  Widget _payments()=>ListView.builder(padding:const EdgeInsets.all(12),itemCount:payments.length,itemBuilder:(c,i){final p=Map<String,dynamic>.from(payments[i]);return Card(child:ListTile(title:Text('${p['name']??''} • ₹${p['amount_inr']??0}',style:const TextStyle(fontWeight:FontWeight.w700)),subtitle:Text('${p['package_name']??''}\n${p['status']??''} • ${p['transaction_id']??''}'),isThreeLine:true,trailing:p['status']=='pending'?Row(mainAxisSize:MainAxisSize.min,children:[IconButton(onPressed:()async{try{await api.request('/admin/payments/${p['id']}/approve',method:'POST');load();}catch(e){_snack(e.toString());}},icon:const Icon(Icons.check_circle_outline)),IconButton(onPressed:()async{final reason=await _reason();if(reason==null)return;try{await api.request('/admin/payments/${p['id']}/reject',method:'POST',body:{'reason':reason});load();}catch(e){_snack(e.toString());}},icon:const Icon(Icons.cancel_outlined))]):null));});
  Widget _ai()=>ListView(padding:const EdgeInsets.all(16),children:[_card('AI Provider Fallback','Gemini → OpenRouter → Groq → Cerebras → Mistral → DeepSeek → Together → xAI → Pollinations. Only configured/accepted providers are used.'),_card('Voice','Gemini 3.1 Flash Live with realtime audio, interruption/VAD and Google Search grounding.'),_card('Limits','No provider is treated as unlimited. When all configured providers are exhausted, the app reports the exhaustion state.')]);
  Widget _cms()=>ListView.builder(padding:const EdgeInsets.all(12),itemCount:cms.length,itemBuilder:(c,i){final x=Map<String,dynamic>.from(cms[i]);return Card(child:ListTile(title:Text('${x['title']??x['item_key']??''}',style:const TextStyle(fontWeight:FontWeight.w700)),subtitle:Text('${x['item_key']??''} • enabled: ${x['is_enabled']??false}'),trailing:Switch(value:x['is_enabled']==true,onChanged:(v)async{try{await api.request('/admin/cms/items/${x['id']}/toggle',method:'POST',body:{'isEnabled':v});load();}catch(e){_snack(e.toString());}})));});
  Widget _stat(String t,d)=>Container(width:155,padding:const EdgeInsets.all(16),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(18),border:Border.all(color:const Color(0xffe4e7ec))),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(t,style:const TextStyle(color:Colors.black54)),const SizedBox(height:8),Text('${d??0}',style:const TextStyle(fontSize:24,fontWeight:FontWeight.w900))]));
  Widget _card(String title,String text)=>Card(child:Padding(padding:const EdgeInsets.all(18),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(title,style:const TextStyle(fontSize:17,fontWeight:FontWeight.w800)),const SizedBox(height:7),Text(text)])));
  Future<String?> _reason()async{final c=TextEditingController();return showDialog<String>(context:context,builder:(d)=>AlertDialog(title:const Text('Rejection reason'),content:TextField(controller:c,autofocus:true,decoration:const InputDecoration(hintText:'Reason')),actions:[TextButton(onPressed:()=>Navigator.pop(d),child:const Text('Cancel')),FilledButton(onPressed:()=>Navigator.pop(d,c.text.trim()),child:const Text('Reject'))]));}
  void _snack(Object e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(e.toString().replaceFirst('Exception: ',''))));}
}
